###
GET http://localhost:8090/api/cars/cars
Accept: application/json

###
GET http://localhost:8090/api/cars/cars/10
Accept: application/json


###
POST http://localhost:8090/api/cars/cars
Content-Type: application/json

{
  "brand": "",
  "model": "",
  "year": 2025,
  "price": 10000
}


###
PUT http://localhost:8090/api/cars/cars/12
Content-Type: application/json

{
  "model": "2026",
  "year": 2026,
  "price": 110000
}

###
DELETE http://localhost:8090/api/cars/cars/12
Accept: application/json