###
GET http://localhost:8090/api/cars/cars
Accept: application/json

###
GET http://localhost:8090/api/cars/cars/12
Accept: application/json


###
POST http://localhost:8090/api/cars/cars
Content-Type: application/json

{
  "brand": "BMW",
  "model": "2025",
  "year": 2025,
  "price": 100000
}