###
GET http://localhost:8090/api/cars
Accept: application/json
Authorization: Basic user:f10b5d46-6e92-432f-a450-d073ed336585
###
GET http://localhost:8090/api/cars/10
Accept: application/json
Authorization: Basic user:f10b5d46-6e92-432f-a450-d073ed336585



###
POST http://localhost:8090/api/cars/
Content-Type: application/json
Authorization: Basic user:f10b5d46-6e92-432f-a450-d073ed336585


{
  "brand": "sada",
  "model": "sasad",
  "year": 2025,
  "price": 10000
}


###
PUT http://localhost:8090/api/cars/2
Content-Type: application/json
Authorization: Basic user:f10b5d46-6e92-432f-a450-d073ed336585

{
  "model": "2026",
  "year": 2026,
  "price": 110000
}

###
DELETE http://localhost:8090/api/cars/2
Accept: application/json
Authorization: Basic user:f10b5d46-6e92-432f-a450-d073ed336585
